// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node prisma/seed.ts",
  },
  datasource: {
    // 마이그레이션은 PgBouncer(pooled)가 아닌 direct connection 사용 권장
    // Dev 환경(DIRECT_URL 미설정)에서는 DATABASE_URL로 fallback
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
